language: python
python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip3 install -r requirements.txt
  - pip3 install pylint codecov coverage
# command to run tests
script:
  - coverage run -m unittest tests/test_*.py
  - pylint "$(pwd)"

after_success:
  - codecov